### PR TITLE
[HOLD] Convert to scala

### PR DESCRIPTION
**Pull request by BusyByte**
Please don't merge just want some review.

### CODE REVIEW

**Comment by BusyByte** [comment]
@raxod502 can you review this and see if it matches the original?
If you have questions let me know.
There are a lot of things I want to change still but this compiles and there are no warnings which is a start.

**Comment by raxod502** [comment]
I'm happy to advise but I'm really not sure what useful review I could provide. Because the original code is so horrifying, there's basically no way for me to tell whether the new version works the same or not (especially as I don't know Scala). I did notice, on running the project, that the resource paths don't seem to be configured correctly (textures can't be loaded).

**Comment by BusyByte** [comment]
@raxod502 I'll check that out, thanks

**Comment by BusyByte** [comment]
@raxod502 I fixed the issue however it still can't find 
`backgrounds/solid/empty.png` which seems to be missing from that folder.
Do you know what that image was?

**Comment by raxod502** [comment]
This is related to your question at https://github.com/raxod502/TerraFrame/issues/8.

> Note that item ID 0 corresponds to "empty" and block ID 0 corresponds to "air". Thus there is no need to load textures for them.

Since the textures for item ID 0 and block ID 0 are both transparent, there are no textures for them. That's why all the loops for loading textures skip index 0.

(To be explicit, `empty` is the name of item 0.)

**Comment by voidnull000** [comment]
but why scala

**Pull request closed without merging**
