### PR TITLE
Remove bad code

### PR DESCRIPTION
**Pull request by djmcgill**

### CODE REVIEW

**Comment by raxod502** [comment]
:+1: I like it but unfortunately I don't think we can merge for reasons of backward compatibility.

**Review by FlorianWendelborn — APPROVED** [review]

**Comment by anaskhan96** [comment]
I tried this fork and it makes the game lightning fast. Best optimization imo

**Comment by sn42** [comment]
This pull request fixes an ArrayIndexOutOfBoundsException when you click ingame. Like it.

**Comment by eshrh** [comment]
anyone else here from reddit

**Comment by craftpip** [comment]
Damn, a clever joke on GitHub. 🥇

**Comment by voidnull000** [comment]
ah man

**Pull request closed without merging**
